version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  bot:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}

    container_name: bot
    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env
    environment:
      HTTP_PROXY: http://proxy:2080
      HTTPS_PROXY: http://proxy:2080
      MYSQL_HOST: db
    # ports:
    # - "${SUB_PORT}:${SUB_PORT}"
    restart: unless-stopped

  proxy:
    image: sagernet/sing-box:latest
    container_name: proxy
    restart: always
    volumes:
      - ./sing-box:/etc/sing-box/
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
